package presentation;

import business.dataModel.Jogador;
import business.dataModel.Opcao;
import business.dataModel.Partida;
import business.dataModel.Pergunta;
import business.dataModel.RondaJogo;
import business.dataModel.Services;
import com.mysql.cj.conf.PropertyKey;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import persistence.LigacaoBD;


/**
 *
 * @author formando
 */
public class Jogo extends javax.swing.JDialog {

    // Criei estas variaveis de instancia para que estas variaveis sejam conhecidas dentro desta classe até o jogo encerrar
    private Services service = new Services();
    private int nivelJogo = 1;
    //Criar um array list dos 4 botões
    private ArrayList<JButton> botoesopcoes = new ArrayList<>();
    //Criar um array list para adiconar um prémios
    private ArrayList<JLabel> premios = new ArrayList<>();
    //Criar um objeto da classe GameOver para conseguir usar
    private GameOver fimJogo = new GameOver(null, true);
    //Criar um objeto da classe Winner para conseguir usar 
    private Winner winner = new Winner(null, true);
    //Ir buscar a pergunta selecionada e guardar na variavel PerguntaSelecionada
    private Pergunta perguntaSelecionda = service.pergunta(nivelJogo);

    /**
     * Creates new form Jogo
     */
    public Jogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Adicionar ao Array List os 4 botões
        botoesopcoes.add(btnOpcao1);
        botoesopcoes.add(btnOpcao2);
        botoesopcoes.add(btnOpcao3);
        botoesopcoes.add(btnOpcao4);
        //Adicionar ao Array List os prémios
        premios.add(lb100);
        premios.add(lb200);
        premios.add(lb300);
        premios.add(lb400);
        premios.add(lb500);
        premios.add(lb600);
        premios.add(lb700);
        premios.add(lb800);
        premios.add(lb900);
        premios.add(lb1000);
        //Adicionar a primeira pergunta ao ecra
        pergunta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelGeral = new javax.swing.JPanel();
        Premios = new javax.swing.JPanel();
        lb100 = new javax.swing.JLabel();
        lb200 = new javax.swing.JLabel();
        lb300 = new javax.swing.JLabel();
        lb400 = new javax.swing.JLabel();
        lb500 = new javax.swing.JLabel();
        lb600 = new javax.swing.JLabel();
        lb700 = new javax.swing.JLabel();
        lb800 = new javax.swing.JLabel();
        lb900 = new javax.swing.JLabel();
        lb1000 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ProximaPergunta = new javax.swing.JPanel();
        btnProximaPergunta = new javax.swing.JToggleButton();
        PainelPergunta = new javax.swing.JPanel();
        PainelOpcoes = new javax.swing.JPanel();
        btnOpcao1 = new javax.swing.JButton();
        btnOpcao2 = new javax.swing.JButton();
        btnOpcao3 = new javax.swing.JButton();
        btnOpcao4 = new javax.swing.JButton();
        lbPergunta = new javax.swing.JLabel();
        NomeJogador = new javax.swing.JPanel();
        lbNomeJogador = new javax.swing.JLabel();
        lbJogador = new javax.swing.JLabel();
        NivelJogo = new javax.swing.JPanel();
        lbNivel = new javax.swing.JLabel();
        lbNivelJogo = new javax.swing.JLabel();
        Ajudas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAjuda50_50 = new javax.swing.JButton();
        btnAjudaMudarPergunta = new javax.swing.JButton();
        lbTimer = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PainelGeral.setBackground(new java.awt.Color(139, 167, 193));

        Premios.setBackground(new java.awt.Color(139, 167, 193));
        Premios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb100.setBackground(new java.awt.Color(0, 76, 153));
        lb100.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lb100.setForeground(new java.awt.Color(255, 255, 255));
        lb100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb100.setText("100€");
        lb100.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb100.setOpaque(true);

        lb200.setBackground(new java.awt.Color(0, 76, 153));
        lb200.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lb200.setForeground(new java.awt.Color(255, 255, 255));
        lb200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb200.setText("200€");
        lb200.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb200.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb200.setOpaque(true);

        lb300.setBackground(new java.awt.Color(0, 76, 153));
        lb300.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb300.setForeground(new java.awt.Color(255, 255, 255));
        lb300.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb300.setText("300€");
        lb300.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb300.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb300.setOpaque(true);

        lb400.setBackground(new java.awt.Color(0, 76, 153));
        lb400.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lb400.setForeground(new java.awt.Color(255, 255, 255));
        lb400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb400.setText("400€");
        lb400.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb400.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb400.setOpaque(true);

        lb500.setBackground(new java.awt.Color(0, 76, 153));
        lb500.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lb500.setForeground(new java.awt.Color(255, 255, 255));
        lb500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb500.setText("500€");
        lb500.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb500.setOpaque(true);

        lb600.setBackground(new java.awt.Color(0, 76, 153));
        lb600.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lb600.setForeground(new java.awt.Color(255, 255, 255));
        lb600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb600.setText("600€");
        lb600.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb600.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb600.setOpaque(true);

        lb700.setBackground(new java.awt.Color(0, 76, 153));
        lb700.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb700.setForeground(new java.awt.Color(255, 255, 255));
        lb700.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb700.setText("700€");
        lb700.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb700.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb700.setOpaque(true);

        lb800.setBackground(new java.awt.Color(0, 76, 153));
        lb800.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        lb800.setForeground(new java.awt.Color(255, 255, 255));
        lb800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb800.setText("800€");
        lb800.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb800.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb800.setOpaque(true);

        lb900.setBackground(new java.awt.Color(0, 76, 153));
        lb900.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lb900.setForeground(new java.awt.Color(255, 255, 255));
        lb900.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb900.setText("900€");
        lb900.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb900.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb900.setOpaque(true);

        lb1000.setBackground(new java.awt.Color(0, 76, 153));
        lb1000.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb1000.setForeground(new java.awt.Color(255, 255, 255));
        lb1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1000.setText("1000€");
        lb1000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb1000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb1000.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setText("PRÉMIOS");

        javax.swing.GroupLayout PremiosLayout = new javax.swing.GroupLayout(Premios);
        Premios.setLayout(PremiosLayout);
        PremiosLayout.setHorizontalGroup(
            PremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PremiosLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lb200, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PremiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb400, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(PremiosLayout.createSequentialGroup()
                .addGroup(PremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PremiosLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lb300, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PremiosLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lb500, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PremiosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lb600, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PremiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb700, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PremiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(PremiosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lb800, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(PremiosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb900, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PremiosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PremiosLayout.setVerticalGroup(
            PremiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PremiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lb1000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb900)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb800)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb700)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb600)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb500)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb400)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb300)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb200)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb100)
                .addContainerGap())
        );

        ProximaPergunta.setBackground(new java.awt.Color(139, 167, 193));

        btnProximaPergunta.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        btnProximaPergunta.setText("Próxima Pergunta");
        btnProximaPergunta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProximaPergunta.setEnabled(false);
        btnProximaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaPerguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProximaPerguntaLayout = new javax.swing.GroupLayout(ProximaPergunta);
        ProximaPergunta.setLayout(ProximaPerguntaLayout);
        ProximaPerguntaLayout.setHorizontalGroup(
            ProximaPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProximaPerguntaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProximaPerguntaLayout.setVerticalGroup(
            ProximaPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProximaPergunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PainelPergunta.setBackground(new java.awt.Color(139, 167, 193));
        PainelPergunta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PainelPergunta.setToolTipText("");

        PainelOpcoes.setBackground(new java.awt.Color(139, 167, 193));

        btnOpcao1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOpcao1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpcao1.setOpaque(true);
        btnOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao1ActionPerformed(evt);
            }
        });

        btnOpcao2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOpcao2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcao2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpcao2.setOpaque(true);
        btnOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao2ActionPerformed(evt);
            }
        });

        btnOpcao3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOpcao3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcao3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpcao3.setOpaque(true);
        btnOpcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao3ActionPerformed(evt);
            }
        });

        btnOpcao4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOpcao4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOpcao4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpcao4.setOpaque(true);
        btnOpcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelOpcoesLayout = new javax.swing.GroupLayout(PainelOpcoes);
        PainelOpcoes.setLayout(PainelOpcoesLayout);
        PainelOpcoesLayout.setHorizontalGroup(
            PainelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpcao1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(btnOpcao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpcao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpcao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelOpcoesLayout.setVerticalGroup(
            PainelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOpcoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcao4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lbPergunta.setBackground(new java.awt.Color(255, 255, 255));
        lbPergunta.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lbPergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPergunta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPergunta.setOpaque(true);

        javax.swing.GroupLayout PainelPerguntaLayout = new javax.swing.GroupLayout(PainelPergunta);
        PainelPergunta.setLayout(PainelPerguntaLayout);
        PainelPerguntaLayout.setHorizontalGroup(
            PainelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PainelPerguntaLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(PainelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        PainelPerguntaLayout.setVerticalGroup(
            PainelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NomeJogador.setBackground(new java.awt.Color(139, 167, 193));
        NomeJogador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NomeJogador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbNomeJogador.setBackground(new java.awt.Color(139, 167, 193));
        lbNomeJogador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNomeJogador.setText("Jogador:");
        lbNomeJogador.setOpaque(true);

        lbJogador.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbJogador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbJogador.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout NomeJogadorLayout = new javax.swing.GroupLayout(NomeJogador);
        NomeJogador.setLayout(NomeJogadorLayout);
        NomeJogadorLayout.setHorizontalGroup(
            NomeJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomeJogadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNomeJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NomeJogadorLayout.setVerticalGroup(
            NomeJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomeJogadorLayout.createSequentialGroup()
                .addGroup(NomeJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        NivelJogo.setBackground(new java.awt.Color(139, 167, 193));
        NivelJogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNivel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNivel.setText("Nivel de Jogo Atual:");

        lbNivelJogo.setBackground(new java.awt.Color(139, 167, 193));
        lbNivelJogo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbNivelJogo.setOpaque(true);

        javax.swing.GroupLayout NivelJogoLayout = new javax.swing.GroupLayout(NivelJogo);
        NivelJogo.setLayout(NivelJogoLayout);
        NivelJogoLayout.setHorizontalGroup(
            NivelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NivelJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNivelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NivelJogoLayout.setVerticalGroup(
            NivelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NivelJogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NivelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNivelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Ajudas.setBackground(new java.awt.Color(139, 167, 193));
        Ajudas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("AJUDAS");

        btnAjuda50_50.setBackground(new java.awt.Color(0, 76, 153));
        btnAjuda50_50.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnAjuda50_50.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuda50_50.setText("50/50");
        btnAjuda50_50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjuda50_50.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAjuda50_50.setMaximumSize(new java.awt.Dimension(60, 60));
        btnAjuda50_50.setOpaque(true);
        btnAjuda50_50.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAjuda50_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjuda50_50ActionPerformed(evt);
            }
        });

        btnAjudaMudarPergunta.setBackground(new java.awt.Color(0, 76, 153));
        btnAjudaMudarPergunta.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnAjudaMudarPergunta.setForeground(new java.awt.Color(255, 255, 255));
        btnAjudaMudarPergunta.setText("Mudar Pergunta");
        btnAjudaMudarPergunta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjudaMudarPergunta.setMaximumSize(new java.awt.Dimension(60, 60));
        btnAjudaMudarPergunta.setOpaque(true);
        btnAjudaMudarPergunta.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAjudaMudarPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaMudarPerguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjudasLayout = new javax.swing.GroupLayout(Ajudas);
        Ajudas.setLayout(AjudasLayout);
        AjudasLayout.setHorizontalGroup(
            AjudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjudasLayout.createSequentialGroup()
                .addGroup(AjudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AjudasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjuda50_50, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjudaMudarPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AjudasLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AjudasLayout.setVerticalGroup(
            AjudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjudasLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AjudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjuda50_50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjudaMudarPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbTimer.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PainelGeralLayout = new javax.swing.GroupLayout(PainelGeral);
        PainelGeral.setLayout(PainelGeralLayout);
        PainelGeralLayout.setHorizontalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addComponent(NomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProximaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelGeralLayout.createSequentialGroup()
                                .addComponent(NivelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(lbTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ajudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PainelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Premios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        PainelGeralLayout.setVerticalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Premios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NivelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ajudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PainelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProximaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao1ActionPerformed
        validarResposta(0, btnOpcao1);
    }//GEN-LAST:event_btnOpcao1ActionPerformed

    private void btnOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao2ActionPerformed
        validarResposta(1, btnOpcao2);
    }//GEN-LAST:event_btnOpcao2ActionPerformed

    private void btnOpcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao3ActionPerformed
        validarResposta(2, btnOpcao3);
    }//GEN-LAST:event_btnOpcao3ActionPerformed

    private void btnOpcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao4ActionPerformed
        validarResposta(3, btnOpcao4);
    }//GEN-LAST:event_btnOpcao4ActionPerformed

    private void btnProximaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaPerguntaActionPerformed
        //Quando um utilizador nao selecionar nenhuma preencherBotoes aparecer uma caixa de texto a informar que nao selecionou nenhuma opção
        btnProximaPergunta.setEnabled(false);
        nivelJogo=nivelJogo+1;
        perguntaSelecionda=service.pergunta(nivelJogo);
        pergunta();
           
            
    }//GEN-LAST:event_btnProximaPerguntaActionPerformed

    private void btnAjuda50_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjuda50_50ActionPerformed
      ajuda50_50();
     
    }//GEN-LAST:event_btnAjuda50_50ActionPerformed

    private void btnAjudaMudarPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaMudarPerguntaActionPerformed
          mudarPergunta();
        
    }//GEN-LAST:event_btnAjudaMudarPerguntaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ajudas;
    private javax.swing.JPanel NivelJogo;
    private javax.swing.JPanel NomeJogador;
    private javax.swing.JPanel PainelGeral;
    private javax.swing.JPanel PainelOpcoes;
    private javax.swing.JPanel PainelPergunta;
    private javax.swing.JPanel Premios;
    private javax.swing.JPanel ProximaPergunta;
    private javax.swing.JButton btnAjuda50_50;
    private javax.swing.JButton btnAjudaMudarPergunta;
    private javax.swing.JButton btnOpcao1;
    private javax.swing.JButton btnOpcao2;
    private javax.swing.JButton btnOpcao3;
    private javax.swing.JButton btnOpcao4;
    private javax.swing.JToggleButton btnProximaPergunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb100;
    private javax.swing.JLabel lb1000;
    private javax.swing.JLabel lb200;
    private javax.swing.JLabel lb300;
    private javax.swing.JLabel lb400;
    private javax.swing.JLabel lb500;
    private javax.swing.JLabel lb600;
    private javax.swing.JLabel lb700;
    private javax.swing.JLabel lb800;
    private javax.swing.JLabel lb900;
    private javax.swing.JLabel lbJogador;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNivelJogo;
    private javax.swing.JLabel lbNomeJogador;
    private javax.swing.JLabel lbPergunta;
    private javax.swing.JLabel lbTimer;
    // End of variables declaration//GEN-END:variables

    //Método para ir buscar uma pergunta
    public void pergunta() {
        
        manutencaoBotoes();
        preencherBotoes(perguntaSelecionda);
        lbPergunta.setText(perguntaSelecionda.getTexto());
        lbNivelJogo.setText(nivelJogo+"");
        
    }

    //Ir buscar as opcoes
    public void preencherBotoes(Pergunta pergunta) {
        service.opcao(pergunta);
        //Cria uma array com as opcoes correspondetes á pergunta atual
        ArrayList<Opcao> opcoes = pergunta.getOpcao();

        for (int i = 0; i < botoesopcoes.size(); i++) {
            //Adiciona em cada botao um texto da preencherBotoes correspondente
            botoesopcoes.get(i).setText(opcoes.get(i).getTexto());
        }

    }

    // Método para validar uma resposta
    private void validarResposta(int indice, javax.swing.JButton botaoClicado) {
        
        if(service.validarResposta(indice)&&nivelJogo==10)
        {
            botaoClicado.setBackground(Color.GREEN);
            colorirPremios(nivelJogo);
            bloquearBotoes(botaoClicado);
            winner.setLocationRelativeTo(null);
            winner.setTitle("WINNER");
            winner.setVisible(true);
            this.dispose();
        }
        else if(service.validarResposta(indice))
        {
            botaoClicado.setBackground(Color.GREEN);
            bloquearBotoes(botaoClicado);
            btnProximaPergunta.setEnabled(true);
            colorirPremios(nivelJogo);
            service.guardarPremio(premios.get(service.indicePremio()).getText());

            
        }
        else{
            botaoClicado.setBackground(Color.red);
            fimJogo.premioGanho(service.mostrarPremio());
            fimJogo.setLocationRelativeTo(null);
            fimJogo.setTitle("Game Over");
            fimJogo.setVisible(true);
            
            this.dispose();
        }
       
    }

    //Método para colocar fazer um reset ás cores aos bloqueios dos botões
    private void manutencaoBotoes() {
        //Colocar a cor natural
        btnOpcao1.setBackground(Color.LIGHT_GRAY);
        btnOpcao2.setBackground(Color.LIGHT_GRAY);
        btnOpcao3.setBackground(Color.LIGHT_GRAY);
        btnOpcao4.setBackground(Color.LIGHT_GRAY);
        //Tornar os botões clicáveis
        btnOpcao1.setEnabled(true);
        btnOpcao2.setEnabled(true);
        btnOpcao3.setEnabled(true);
        btnOpcao4.setEnabled(true);

    }

    //Adicionar o nome de quem está a jogar
    public void NomeJogador(String nome) {
        lbJogador.setText(nome);
    }

    // Método para bloquear os botões
    private void bloquearBotoes(javax.swing.JButton botaoClicado) {

        if (botaoClicado == btnOpcao1) {
            btnOpcao2.setEnabled(false);
            btnOpcao3.setEnabled(false);
            btnOpcao4.setEnabled(false);
            
        } else if (botaoClicado == btnOpcao2) {
            btnOpcao1.setEnabled(false);
            btnOpcao3.setEnabled(false);
            btnOpcao4.setEnabled(false);
            
        } else if (botaoClicado == btnOpcao3) {
            btnOpcao1.setEnabled(false);
            btnOpcao2.setEnabled(false);
            btnOpcao4.setEnabled(false);
            
        } else {
            btnOpcao1.setEnabled(false);
            btnOpcao2.setEnabled(false);
            btnOpcao3.setEnabled(false);
        }
    }

    //Método para colorir os Premios
    private void colorirPremios(int indicePremio) {

        for (int i = 0; i <= premios.size(); i++) {
            premios.get(indicePremio - 1).setBackground(Color.green);

        }
    }

    //Método para usar a Ajuda de Mudar de Pergunta
    private void mudarPergunta() {

        perguntaSelecionda = service.perguntaAjuda(nivelJogo);
        preencherBotoes(perguntaSelecionda);
        lbPergunta.setText(perguntaSelecionda.getTexto());
        btnAjudaMudarPergunta.setEnabled(false);
    }

    //Método para usar a Ajuda de 50/50
    private void ajuda50_50() {

        ArrayList<Opcao> opcoes = perguntaSelecionda.getOpcao();
        int numeroResposta = 0;
        for (int i = 0; i < opcoes.size(); i++) {
            if (opcoes.get(i).getResposta() == false && numeroResposta < 2) {
                botoesopcoes.get(i).setEnabled(false);
                numeroResposta = numeroResposta + 1;
            }
        }
        btnAjuda50_50.setEnabled(false);

    }

}
