
package presentation;

import business.dataModel.Jogador;
import business.dataModel.Partida;
import business.dataModel.RondaJogo;
import business.dataModel.Services;
import java.awt.Color;
import javax.swing.JOptionPane;
import persistence.LigacaoBD;

/**
 *
 * @author formando
 */
public class QuemQuerSerMilionario extends javax.swing.JFrame {

    /**
     * Creates new form QuemQuerSerMilionario
     */
    public QuemQuerSerMilionario() {
        initComponents();
        this.setTitle("Quem Quer Ser Milionário");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnComecar = new javax.swing.JToggleButton();
        lbImagem = new javax.swing.JLabel();
        Jogador = new javax.swing.JPanel();
        lbNomeJogador = new javax.swing.JLabel();
        txtNomeJogador = new javax.swing.JTextField();
        lbDataNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(139, 167, 193));

        btnComecar.setBackground(new java.awt.Color(0, 76, 153));
        btnComecar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnComecar.setForeground(new java.awt.Color(255, 255, 255));
        btnComecar.setText("Começar");
        btnComecar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComecar.setOpaque(true);
        btnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarActionPerformed(evt);
            }
        });

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/QuemQuerSerMilion_rio-Photoroom.png"))); // NOI18N

        Jogador.setBackground(new java.awt.Color(139, 167, 193));
        Jogador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNomeJogador.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbNomeJogador.setText("Nome Jogador :");

        lbDataNascimento.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbDataNascimento.setText("Data Nascimento:");

        javax.swing.GroupLayout JogadorLayout = new javax.swing.GroupLayout(Jogador);
        Jogador.setLayout(JogadorLayout);
        JogadorLayout.setHorizontalGroup(
            JogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JogadorLayout.createSequentialGroup()
                        .addComponent(lbNomeJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(JogadorLayout.createSequentialGroup()
                        .addComponent(txtNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JogadorLayout.createSequentialGroup()
                        .addGroup(JogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataNascimento)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JogadorLayout.setVerticalGroup(
            JogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jogador, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComecar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lbImagem)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarActionPerformed

        
            String nome = txtNomeJogador.getText();
            String data = txtDataNascimento.getText();
            Services service = new Services();
            
            String resultado = service.validarEInserirJogador(nome, data);
            
            //Se a string resultado não vier vazia significa que ouve um erro
            if(!resultado.isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, resultado);
            }
            else{
                 // Se tudo estiver direito insere
                service.validarEInserirJogador(nome, data);

                Jogo jogo = new Jogo(this, true);
                jogo.NomeJogador(nome);
                jogo.setLocationRelativeTo(null);
                jogo.setTitle("Quem Quer Ser Milionário");
                jogo.setVisible(true);
            }
    }//GEN-LAST:event_btnComecarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuemQuerSerMilionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuemQuerSerMilionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuemQuerSerMilionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuemQuerSerMilionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuemQuerSerMilionario().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jogador;
    private javax.swing.JToggleButton btnComecar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbNomeJogador;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNomeJogador;
    // End of variables declaration//GEN-END:variables
private boolean validarFormatoData(String data) {
        // Esta expressão regular verifica se o texto segue o padrão: 
        // 2 dígitos / 2 dígitos / 4 dígitos
        return data.matches("\\d{2}/\\d{2}/\\d{4}");
    }
}
